### ISSUE TITLE
Battery Life and Dual state. 

### ISSUE THREAD

**Issue by spREGR** [meichthys/window_sensors#2]
hello 👋 thanks for developing this great project. I have a question

How long does the battery last. 
Also , can we not use SPDT reed switch which gives but normally open and normally closed states.

**Comment by meichthys** [comment]
@puneit-hassio  
So far the batteries seem to last about 5 months on a charge. I still have plans to add to this project by including a 3d printed charger for the batteries listed in the readme. Not sure when i'll get around to this though.

As for the reed switches, you should be able to use anything that results in a normally closed state so the battery doesn't drain. (Even if you put the device in deep-sleep mode, the battery will drain within a few days). 

An alternate configuration would be to use a normally open reed switch and then place your magnet near the door stopper. (This wouldn't normally be optimal since the open door wouldn't always be in the perfect spot to trigger the reed switch.)

**Comment by Ulrar** [comment]
Speaking of chargers, what do you use to charge these batteries ?

**Comment by meichthys** [comment]
@Ulrar I use [this](https://www.amazon.com/dp/B00466PKE0/ref=cm_sw_r_cp_awdb_t1_9rtWEbD3DW83K) because I had it laying around, but any single cell lipo battery charger should work. I just clip the alligator clips on the positive and negative terminals. It works well, but I may improve the usability some by printing a battery charger port that we could use to “plug“ the batteries into for easier charging.
