### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by ClouDevelopment** [meichthys/window_sensors#3]
Love the project.  

I am working on my first sensor, but was wondering how long the battery works before you need to recharge it?  Speaking of recharging the battery, do you have an easy way to do this already?

Thanks
-Steve

**Comment by meichthys** [comment]
Hi Steve I think there was another issue where I answered some questions on battery life, but in general they seem to last about a year or so if the windows are not opened on a regular basis. If used on a door or something more regularly used, it will probably be a few months. 

Because my batteries are mostly still good, I haven't designed a re-charging port yet, but I probably will at some point.

**Comment by GeneArnold** [comment]
So are you soldering the battery directly to the chip? I was looking at your design and could not tell if you just lay the battery on top of the wires or solder them. Thank you.

**Comment by meichthys** [comment]
The battery slides on top of the contact wires, so no soldering needed. The battery cover provides enough pressure to keep the battery connected. 👍

**Comment by meichthys** [comment]
And for a battery update, I've had many of the sensors installed for over a year now and most of them are still on their first charge! I've replaced/recharged a few batteries that were installed on sensors that get used much more often.

**Comment by meichthys** [comment]
Another update.. still going strong on a few of the original batteries (the ones that were used on windows which do not open often).

**Comment by meichthys** [comment]
The batteries finally died. So about two years on a new battery.
